export const appRoutes = {
  login: "/login",
  forgotPassword: "/forgot-password",
  authConfirm: "/auth/confirm",
  terms: "/terms",
  updatePassword: "/account/update-password",
  privacySettings: "/account/privacy",
  privacySettingsPreview: "/account/privacy/preview",
  dpa: "/account/privacy/dpa",
  accountApi: "/account/api",
  privacy: "/privacy",
  cookies: "/cookies",
  dashboard: "/dashboard",
  surveys: "/surveys",
  surveyNew: "/surveys/new",
  surveyDetail: (surveyId: string) => `/surveys/${surveyId}`,
  surveyEdit: (surveyId: string) => `/surveys/${surveyId}/edit`,
  publicSurveyLink: (linkToken: string) => `/s/${linkToken}`,
  publicSurveyFeedback: (linkToken: string) => `/s/${linkToken}/feedback`,
  publicSurveyPrivacy: (linkToken: string) => `/s/${linkToken}/privacy`,
  publicSurveyThankYou: (linkToken: string) => `/s/${linkToken}/thank-you`,
  surveyAnalytics: (surveyId: string) => `/surveys/${surveyId}/analytics`,
  surveyAnalyticsV2: (surveyId: string) => `/surveys/${surveyId}/analytics-v2`,
  instrumentHealthMethodology: "/docs/instrument-health",
  interoperabilityApiDocs: "/docs/api",
  interoperabilityOpenApi: "/api/v1/openapi",
} as const;
